name: Build and Deploy uclock app to uclock.me 

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Verify Node.js version
        run: node -v

      - name: Install dependencies
        run: npm install

      - name: Create .env file
        run: |
          echo "VITE_APP_NODE_API=${{ secrets.VITE_APP_NODE_API }}" > .env

      - name: Build React app
        run: npm run build

      - name: Deploy to FTP Server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./build/   # Ensure this ends with a slash
